BCDevOps/developer-experience

apps/requestron/src/index.ts
apps/requestron/src/lib/closeComment.ts
apps/requestron/src/lib/milestone.ts

requestron will now add a comment when an issue is closed in the devops-requests repo with a few details:
1. what closure of the ticket means
2. reminder to accept an invite if appropriate
3. where to ask for additional support

added generic closing comment

---

docs/WhyAmIGettingThisEmail.md

added a quick markdown file to provide as a link to all email communications with POs.

add communication FAQ

---

docs/KeycloakMigration.md

Keeping this doc updated during the migration.

KC migration doc

---

apps/requestron/lib/closeComment.js

the closing comments now provide specific details for the new request types.

added quota-type and new-request-type

---

docs/HumanHelp.md

this is a doc that will be put on devhub to serve as the new target for the "human help" link on the devops-requests repo.

adding human help doc

---

docs/KeycloakMigration.md
docs/kcMigration/KeycloakMigration.md
docs/kcMigration/kc-admin.md

This document is to be added to devhub under OCP4 topic/journey. Notice will also be included in the rocketchat sso channel once ready.

KeyCloak service migration doc

---

docs/Onboarding.md
docs/onboarding.md

This document is made to supplement the on-boarding journey. It speaks about the preliminaries prior to booking the alignment meeting.

Add onboarding step 1 document

---

docs/resource-tuning-recommendations.md

Per assigned check-box  at https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/495

Documented oc one liners for CPU consumption and requests values

---

apps/requestron/lib/index.js
apps/requestron/lib/opsAway.js

put a message in all new tickets about the temporary service unavailability when Cailey and I are both away.

Requestron: ops away comment

---

docs/resource-tuning-recommendations.md

Added a link to Patrick's episode on CPU and memory utilization.
Please let me know if the video link is placed in an incorrect section in the doc..
😄

Update resource tuning doc to include video

---

apps/error-page/package-lock.json
apps/error-page/package.json
apps/error-page/src/app/app.module.ts
apps/error-page/src/app/outof-service-page/outof-service-page.component.html
apps/error-page/src/app/shared/header/header.component.ts
apps/error-page/src/app/unauthorized-page/unauthorized-page.component.ts
apps/error-page/src/index.html

added a message for realm-o-matic service name migration.
also lint fixes and npm package updates.

Maintenance page

---

docs/kcMigration/sso-service-name-migration-notification.md

This message to be added to devhub

update sso migration ref doc

---

apps/requestron/.gitignore
apps/requestron/README.md
apps/requestron/lib/averageTime.js
apps/requestron/lib/closeComment.js
apps/requestron/lib/estimate.js
apps/requestron/lib/index.js
apps/requestron/lib/jwt.js
apps/requestron/lib/milestone.js
apps/requestron/lib/needsResponse.js
apps/requestron/lib/onboarding.js
apps/requestron/lib/opsAway.js
apps/requestron/lib/sprintEpic.js
apps/requestron/lib/staleIssue.js
apps/requestron/lib/swimlane.js
apps/requestron/lib/ticketCount.js
apps/requestron/openshift/dc.yml
apps/requestron/openshift/github-private-key.yaml
apps/requestron/openshift/github-token.yaml
apps/requestron/openshift/repo-secret.yaml
apps/requestron/openshift/requestron-secrets.yaml
apps/requestron/openshift/webhook-secret.yaml
apps/requestron/openshift/zenhub-token.yaml
apps/requestron/package-lock.json
apps/requestron/package.json

This branch includes the following changes:
1. Remove the "welcome to the platform" message when users open a ticket with the openshift-project-set label (since that label is now used for deleting project sets off of 3.11 only).
2. Add a 0.5 estimate to all new tickets.
3. Add all new tickets to the most current sprint goal epic.
4. Add staleness labels and the ability to close very stale tickets.
5. Update the way the bot uses the github API so that it connects via the requestron app and not my personal account.

Requestron: Sprint Goals

---

docs/resiliency-checklist.md

Per [ZH Ticket](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/755)

A Well Behaved App

---

docs/SonarQubeBestPractices

SonarQube best practices for devs and infosec teams

Create SonarQubeBestPractices md

---

apps/artifactory/artifactory-operator/config/rbac/cr-aggregate-artifactrepos-view.yaml
apps/artifactory/artifactory-operator/config/rbac/cr-aggregate-artifactsvcas-admin-edit.yaml
apps/artifactory/artifactory-operator/config/rbac/cr-aggregate-artifactsvcas-view.yaml

looks like roles should have plural CRD names? that seems to have fixed the issue!

artifactory - fixed role config

---

apps/artifactory/artifactory-ha/templates/manifest.yaml.j2

to pull from the redhat repo explicitly

update artifactory url

---

apps/artifactory/DEVHUB-README.md

I did a pretty full re-write of the Artifactory docs in the hopes that our new docs are clearer and more helpful to users!

Artifactory DevHub doc clarification

---

apps/artifactory/DEVHUB-README.md

Just some updates to the README to add all the instructions for how to create/use an Artifactory Project :)

projects documentation

---

apps/artifactory/artifactory-ha/vars-gold.yaml
apps/artifactory/artifactory-ha/vars-klab.yaml
apps/artifactory/artifactory-ha/vars-silver.yaml

Just what it says on the tin :)

added new caching repos

---

apps/artifactory/artifactory-ha/helm/helm-install.yaml
apps/artifactory/artifactory-ha/helm/helm-vars-lab.yaml

This is just a couple of missing bits of the config for the helm version of the Artifactory installation process - nothing too big!

install config changes

---

.github/ISSUE_TEMPLATE/weekly_ccm.md

For example https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2539

Create a template for weekly CCM push tickets
